# Site settings

title:                "Teutonic CSS"
slug-title:           "teutonic-css"
email:                frank@franklaemmer.de
description:          "A modern CSS framework — versatile, well documented. Enjoy a fresh look. Customize at ease."
baseurl:              ""
url:                  "https://teutonic.co" # the base hostname & protocol for your site
twitter_username:     "frank_laemmer"
github_username:      "frank-laemmer"
media-splash-image:   "/img/teutonic-splash-image.jpg"


css_file_docs:        "teutonic.css"
css_file_min:         "teutonic.min.css"
version:              0.7.13
cdn_url:              https://unpkg.com/teutonic-css@0.7.13/teutonic.min.css
licence_url:          https://github.com/fortrabbit/teutonic-css/blob/master/LICENSE
github_download_url:  https://github.com/fortrabbit/teutonic-css/archive/master.zip
github_url:           https://github.com/fortrabbit/teutonic-css
github_scss_url:      https://github.com/fortrabbit/teutonic-css/blob/master/includes
github_gzip_css_url:  https://github.com/fortrabbit/teutonic-css/blob/master/teutonic.css.min.gz?raw=true
github_min_css_url:   https://raw.githubusercontent.com/fortrabbit/teutonic-css/master/teutonic.min.css
github_large_css_url: https://raw.githubusercontent.com/fortrabbit/teutonic-css/master/teutonic.css
keywords:             "CSS utility library, responsive, OOCSS, Pattern Library"
medium_url:           https://medium.com/teutonic-css



# Useful for files that are not generated by jekyll;
# e.g. files or assets that are generated by your build tool.
# The paths are relative to the destination
keep_files:
  - css
  - .gitkeep
# during DEV the css folder will be generated by Gulp
# so it's gonna be overwritten on jekyll build

# where are the actual pages?
# source: jekyll

# where the build will be found, when not on GH pages
destination: docs

# Exclude in generated site
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - package-lock.json
  - LICENSE
  - README.md
  - TODO.md
  - Vagrantfile
  - Dockerfile
  - node_modules
  - .gitignore
  - vendor/
  - .bundle
  - [vendor]
  - [.bundle]


# Collections
collections:
  examples:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path:  "examples/*/"
    values:
      sitemap:   false



# General settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  auto_ids:         true
  toc_levels:       1..6
